In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [6]:
#importing vodka infomation",
vodka_url="http://www.efficientdrinker.com/liquor/"
vodka_data=pd.read_html(vodka_url)
vodka_df=vodka_data[0]
vodka_df=vodka_df.rename(columns={'Brand or Type':'Brand'})
vodka_df['Type']='Vodka'
vodka_df=vodka_df.drop(columns=['ABV','Efficiency','Carbs (g)'])
vodka_df.sample(3)

#importing beer infomation
beer_url="http://www.efficientdrinker.com/beer/complete-calories-abv/"
beer_data=pd.read_html(beer_url)
beer_df=beer_data[0]
beer_df['Type']='Beer'
beer_df=beer_df.drop(columns=['ABV','Efficiency'])
beer_df.head(5)

#importing malt infomation
malt_url="http://www.efficientdrinker.com/wine/malternatives/"
malt_data=pd.read_html(malt_url)
malt_df=malt_data[0]
malt_df['Type']='Malt'
malt_df=malt_df.drop(columns=['ABV','Efficiency'])
malt_df.head(5)

                                  Brand  Calories  Type
0              Truly Spiked & Sparkling       100  Malt
1  Henry's Hard Sparkling Passion Fruit        92  Malt
2     Henry's Hard Sparkling Lemon Lime        93  Malt
3                  Spiked Seltzer Water       140  Malt
4            Mike's Light Hard Lemonade        98  Malt

In [8]:
alc_df=pd.concat([malt_df,beer_df,vodka_df]) #joining all three of the dataframes together\n",
alc_df=alc_df.reset_index() #reseting the index for the one dataframe\n",

#changing the values in data frame to lowercase,
alc_df["Brand"]=alc_df["Brand"].str.lower()
alc_df["Type"]=alc_df["Type"].str.lower()

alc_df.sample(10)

     index                        Brand  Calories  Type
149    127        michelob golden draft       152  beer
32      10       augustiner amber lager       135  beer
26       4            abita purple haze       128  beer
139    117         leinenkugel original       152  beer
4        4   mike's light hard lemonade        98  malt
175    153                  natural ice       130  beer
65      43                    busch ice       136  beer
192    170  ommegang three philosophers       290  beer
44      22             boddington's ale       148  beer
209    187                  redhook ipa       188  beer

In [10]:
def lower_cal(kind,name):
    indi=alc_df[alc_df['Brand']==name].index.item()
    num_cals=alc_df.get_value(indi,'Calories')

    suggest_lowcal=alc_df[ (alc_df["Type"]==kind) & (alc_df["Calories"]<num_cals)]
    suggestions=suggest_lowcal.sample(5)
    
    return suggestions

lower_cal("vodka","fireball")

def get_cal(kind,name): #function that returns the amount of calories in one serving
    indi=alc_df[alc_df['Brand']==name].index.item()
    num_cals=alc_df.get_value(indi,'Calories')
    
    return num_cals

In [11]:
try:
    
    beer_total=0
    vodka_total=0
    malt_total=0
    print("Alcohol Calorie Counter \n")
    
    while True:
        
        user_type=input("Please enter a type of alcohol. Your choices are Beer, Vodka, and Malt. Enter STOP if your finished. \n")
        
        #test to see if user enters stop while ignoring case
        if(user_type.casefold()=='STOP'.casefold()):
            cal_total=beer_total + vodka_total + malt_total
            print("On your night out you drank a total of %.2f calories" %(cal_total ))
            break
            
        #test to see if user enters beer while ignoring case
        elif(user_type.casefold()=="Beer".casefold()):
            user_type="beer"
            while True:
                user_brand=input("Please enter a brand of Beer you had. Enter STOP if your done.\n")
                user_brand=user_brand.lower()

                if(user_brand=="stop"):
                    break

                #preforms calculation and adds calorie count to running sum
                num_drinks=int(input("Please enter the number of drinks of %s you had.\n" %(user_brand)))
                cal_count_beer=get_cal(user_type,user_brand)
                cal_count_beer=cal_count_beer*num_drinks
                beer_total=beer_total+cal_count_beer
                print("While having %d drinks of %s you consumed %.2f calories" %(num_drinks,user_brand,cal_count_beer))
                print("Here are some lower calorie alternatives")
                display(lower_cal(user_type,user_brand))
                
         #test to see if user enters vodka while ignoring case
        elif(user_type.casefold()=="Vodka".casefold()):
            user_type="vodka"
            while True:
                user_brand=input("Please enter a brand of Vodka you had. Enter STOP if your done.\n")
                user_brand=user_brand.lower()

                if(user_brand=="stop"):
                    break
                    
                #preforms calculation and adds calorie count to running sum
                num_drinks=int(input("Please enter the number of shots of %s you had.\n" %(user_brand)))
                cal_count_vodka=get_cal(user_type,user_brand)
                cal_count_vodka=cal_count_vodka*num_drinks
                vodka_total=vodka_total+cal_count_vodka
                print("While having %d shots of %s you consumed %.2f calories" %(num_drinks,user_brand,cal_count_vodka))
                print("Here are some lower calorie alternatives")
                display(lower_cal(user_type,user_brand))
                
        #test to see if user enters beer while ignoring case
        elif(user_type.casefold()=="Malt".casefold()):
            user_type="malt"
            while True:
                user_brand=input("Please enter a brand of Malt liquor you had. Enter STOP if when your done.\n")
                user_brand=user_brand.lower()

                if(user_brand=="stop"):
                    break
                    
                #preforms calculation and adds calorie count to running sum
                num_drinks=int(input("Please enter the number of drinks of %s you had.\n" %(user_brand)))
                cal_count_malt=get_cal(user_type,user_brand)
                cal_count_malt=cal_count_malt*num_drinks
                malt_total=malt_total+cal_count_malt
                print("While having %d drinks of %s you consumed %.2f calories" %(num_drinks,user_brand,cal_count_malt))
                print("Here are some lower calorie alternatives")
                display(lower_cal(user_type,user_brand))

         #check for the user       
        else:
            print("Im sorry one of our alcohol types isn't %s" %(user_type)) 
#prevents error message 
except ValueError:
    print("ERROR: Either that brand was not located in our database or you didn't enter a proper number of drinks")

Alcohol Calorie Counter

Please enter a type of alcohol. Your choices are Beer, Vodka, and Malt. Enter STOP if your finished.
beer
Please enter a brand of Beer you had. Enter STOP if your done.
natural light
Please enter the number of drinks of natural light you had.
4
While having 4 drinks of natural light you consumed 380.00 calories
Here are some lower calorie alternatives

     index                          Brand  Calories  Type
36      14                   beck's light        64  beer
74      52                 corona premier        90  beer
63      41            budweiser select 55        55  beer
198    176  pabst extra light low alcohol        67  beer
158    136       michelob ultra pure gold        85  beer

Please enter a brand of Beer you had. Enter STOP if your done.
stop
Please enter a type of alcohol. Your choices are Beer, Vodka, and Malt. Enter STOP if your finished.
malt
Please enter a brand of Malt liquor you had. Enter if when your done.
twisted tea
Please enter the number of drinks of twisted tea you had.
5
While having 5 drinks of twisted tea you consumed 1100.00 calories
Here are some lower calorie alternatives

    index                              Brand  Calories  Type
6       6                               zima       181  malt
2       2  henry's hard sparkling lemon lime        93  malt
3       3               spiked seltzer water       140  malt
5       5                  twisted tea light       115  malt
21     21          bartles & jaymes original       210  malt

Please enter a brand of Malt liquor you had. Enter if when your done.
stop
Please enter a type of alcohol. Your choices are Beer, Vodka, and Malt. Enter STOP if your finished.
stop
On your night out you drank a total of 1480.00 calories